/* ============================================================
   MONTHLY PLAN GENERATOR
   ============================================================ */
function catCode(category){ return category==='Gaji'?'A':category==='Operasional Rutin'?'B':category==='Operasional Kegiatan'?'C':null; }
function buildPlannedExpenseTxn(monthKey, mo, o){
  const ts=new Date().toISOString();
  return {id:uid(o.source||'plan'), monthKey, month:mo.month, year:mo.year, monthNum:mo.monthNum,
    category:o.category, categoryCode:catCode(o.category), no:null,
    uraian:o.uraian, vol:1, satuan:'bulan', hargaSatuan:o.amount, planned:o.amount, actual:null, type:'expense', txnDate:null,
    source:o.source||'manual', unplanned:false, scheduledDate:null, paymentMethod:o.paymentMethod||null, bankAccount:o.bankAccount||null,
    referenceNumber:null, notes:o.notes||null, vendor:o.vendor||null,
    executionId:null, executionTimestamp:null, execution:null, status:'planned',
    monthlyPlanId:o.monthlyPlanId||null, recurringId:o.recurringId||null,
    history:[{event:'created', ts, note:'Generated by Monthly Plan Generator'}]};
}
function prevMonthKey(monthKey){ const a=keyAbs(monthKey)-1; return mkKey(Math.floor(a/12), (a%12)+1); }
// Non-payroll, non-recurring planned expense items from a month — the only
// things eligible to copy forward (actuals are never copied).
function manualItemsForMonth(monthKey){
  return State.txns.filter(t=>t.monthKey===monthKey && t.type!=='income' && t.source!=='payroll' && !t.recurringId && statusOf(t)!=='cancelled');
}
function buildMonthlyPreview(monthKey, opts){
  const rows=[], warnings=[];
  if(opts.payroll){
    // Part 11: the Monthly Plan CONSUMES payroll committed in Payroll Planning —
    // it never generates payroll independently. Committed payroll already carries
    // its own planned Gaji transaction, so these rows are informational (locked).
    const committed = State.payrollPlans.filter(p=>p.monthKey===monthKey && isPayrollCommitted(p));
    committed.forEach(p=>{
      const txn = payrollTxnOf(p);
      rows.push({type:'payroll', label:`${p.employeeName}${p.contractNumber?' · '+p.contractNumber:''}${p.contractProgress?' · '+p.contractProgress:''}`, category:State.settings.defaultPayrollCategory||'Gaji', planned:num(p.plannedAmount), selected:false, dup:'committed', warn:null, committedTxnId: txn?txn.id:null});
    });
    const cyc = payrollCycleStatus(monthKey);
    if(cyc==='Not Generated') warnings.push('Payroll has not been generated for this month — open Payroll Planning to generate and commit payroll.');
    else if(!committed.length) warnings.push('Payroll generated but not committed yet — commit Ready payroll in Payroll Planning.');
    else if(cyc==='Ready to Commit' || cyc==='In Review' || cyc==='Draft') warnings.push('Some payroll rows are not yet committed — commit them in Payroll Planning to include them.');
  }
  if(opts.recurring){
    recurringDueInMonth(monthKey).forEach(r=>{
      const dupTxn = State.txns.find(t=>t.recurringId===r.id && t.monthKey===monthKey);
      rows.push({type:'recurring', label:r.name, category:r.category||'Operasional Rutin', planned:num(r.defaultAmount), selected:!dupTxn, dup:dupTxn?'duplicate':'new', recurringId:r.id, vendor:r.vendor, paymentMethod:r.paymentMethod, bankAccount:r.bankAccount, warn: num(r.defaultAmount)<=0?'zero-value':null});
    });
  }
  (opts.copyRows||[]).forEach(cr=>{
    const dupTxn = State.txns.find(t=>t.monthKey===monthKey && normStr(t.uraian)===normStr(cr.uraian) && t.category===cr.category);
    rows.push({type:'manual', label:cr.uraian, category:cr.category, planned:num(cr.planned), selected:!dupTxn, dup:dupTxn?'duplicate':'new', warn:null});
  });
  return {monthKey, rows, warnings};
}
function previewTotals(preview){
  const sel = preview.rows.filter(r=>r.selected);
  const by = t=>sel.filter(r=>r.type===t).reduce((s,r)=>s+num(r.planned),0);
  // Payroll is already committed (informational rows) — count all of it.
  const payroll = preview.rows.filter(r=>r.type==='payroll').reduce((s,r)=>s+num(r.planned),0);
  const dup = preview.rows.filter(r=>r.dup==='duplicate').length;
  const missing = preview.rows.filter(r=>r.warn==='missing salary').length;
  const zero = preview.rows.filter(r=>r.warn==='zero-value').length;
  return {payroll, recurring:by('recurring'), manual:by('manual'), total: payroll + sel.filter(r=>r.type!=='payroll').reduce((s,r)=>s+num(r.planned),0), rows:sel.filter(r=>r.type!=='payroll').length, dup, missing, zero};
}
async function commitMonthlyPlan(preview){
  // UX-006C2C-4 (row 20) — COMPOSITE: commits the monthly plan AND creates planned finance
  // transactions. Single top gate (finance.manage) BEFORE the row loop, so a denial creates
  // no transaction and leaves the plan untouched. Payroll rows are not re-created here; they
  // come from Payroll Planning under payroll.manage.
  if(!can(ACTIONS.FINANCE_MANAGE)) return {ok:false, error:'NotAuthorized', created:0};
  const mo = keyToMonthObj(preview.monthKey);
  const plan = ensureMonthlyPlan(preview.monthKey);
  // Payroll rows are consumed from Payroll Planning (already committed) — never
  // re-created here. Only recurring/manual rows create transactions.
  const sel = preview.rows.filter(r=>r.selected && r.dup!=='duplicate' && r.dup!=='committed' && r.type!=='payroll');
  let created=0;
  for(const r of sel){
    const txn = buildPlannedExpenseTxn(preview.monthKey, mo, {
      uraian:r.label, category:r.category, amount:num(r.planned), source:r.type==='recurring'?'recurring':'manual',
      recurringId:r.recurringId||null, vendor:r.vendor||null, paymentMethod:r.paymentMethod||null, bankAccount:r.bankAccount||null, monthlyPlanId:plan.id,
    });
    State.txns.push(txn); plan.committedTxnIds.push(txn.id); created++;
  }
  plan.status='Committed'; plan.committedAt=new Date().toISOString(); plan.updatedAt=plan.committedAt;
  // SPR-082 — the two writes keep their EXISTING ORDER (transactions, then
  // monthly plans) and the existing attempt-all behaviour: a failing first write
  // does not abort the second, so the failure matrix is unchanged. What changes
  // is that both results are now inspected instead of discarded.
  //
  // This is NOT atomic and no rollback is performed or claimed: one storage key
  // is written at a time, so a failure means the commit did not complete — not
  // that nothing was written. An earlier write in the sequence may well have
  // persisted.
  const txnsOk = await persist();
  const plansOk = await persistMonthlyPlans();
  const steps = [{name:'transactions', ok:txnsOk===true}, {name:'monthlyPlans', ok:plansOk===true}];
  const completedSteps = steps.filter(s=>s.ok).map(s=>s.name);
  const failedSteps = steps.filter(s=>!s.ok).map(s=>s.name);
  if(failedSteps.length){
    return {ok:false, error:'MonthlyPlanPersistenceFailed',
      failedStep: failedSteps[0],            // deterministic: first failure in the fixed write order
      failedSteps, completedSteps,
      partialPersistence: completedSteps.length > 0,
      recoveryHint:'RunIntegrityCheckAndReview',
      created, monthlyPlanId:plan.id};
  }
  return {ok:true, created, updated:0, monthlyPlanId:plan.id,
    transactionId: created ? plan.committedTxnIds[plan.committedTxnIds.length-1] : null};
}

function renderMonthlyPlanGenerator(main){
  if(!State.planGenMonth) State.planGenMonth = todayKey();
  const monthKey = State.planGenMonth;
  const mo = keyToMonthObj(monthKey);
  const preview = (State.planPreview && State.planPreview.monthKey===monthKey) ? State.planPreview : null;
  const plan = monthlyPlanFor(monthKey);
  const yearOpts = [];
  for(let y=mo.year-1; y<=mo.year+2; y++) yearOpts.push(y);

  main.innerHTML = `
    <div class="page-head">
      <div><h1>Monthly Plan Generator</h1><p class="desc">Assemble a full monthly plan from payroll, recurring expenses, and copied operational items — then review and commit as planned transactions.</p></div>
      <div class="head-controls">
        <select class="input" id="planMonthSel">${MONTH_ORDER.map((mn,i)=>`<option value="${i+1}" ${mo.monthNum===i+1?'selected':''}>${mn}</option>`).join('')}</select>
        <select class="input" id="planYearSel">${yearOpts.map(y=>`<option ${y===mo.year?'selected':''}>${y}</option>`).join('')}</select>
        <button class="btn btn-accent" id="buildPreview">Build Preview</button>
      </div>
    </div>
    <div class="grid grid-3 stack-section">
      <div class="card stat-card"><div class="stat-label">Plan Status</div><div class="stat-value" style="font-size:16px;">${plan?hrStatusBadge(plan.status,PLAN_STATUS_META):'<span class="faint">Not started</span>'}</div><div class="stat-sub dim">${escapeHtml(mo.month)} ${mo.year}</div></div>
      <div class="card stat-card"><div class="stat-label">Committed Rows</div><div class="stat-value">${plan?plan.committedTxnIds.length:0}</div><div class="stat-sub dim">planned transactions in this month's plan</div></div>
      <div class="card stat-card"><div class="stat-label">Workflow</div><div class="stat-sub dim" style="margin-top:2px;line-height:1.8;">Draft → Reviewed → Committed<br><span class="faint">Approved &amp; Closed are future-ready</span></div></div>
    </div>
    ${(()=>{ const cyc=payrollCycleStatus(monthKey); const committed=State.payrollPlans.filter(p=>p.monthKey===monthKey&&isPayrollCommitted(p)).length; const sect = cyc==='Not Generated'?'Missing':(committed?(State.payrollPlans.some(p=>p.monthKey===monthKey&&p.otChanged)?'Changed':'Committed'):(cyc==='In Review'?'Reviewed':'Generated'));
      return `<div class="card" style="margin-bottom:var(--space-4);border-left:3px solid var(--accent);">
      <h3>Payroll Source <span class="tag">${escapeHtml(sect)}</span></h3>
      <p class="hint" style="margin:-6px 0 10px;">The Monthly Plan consumes payroll committed in Payroll Planning — it does not generate payroll here. ${committed?`${committed} committed payroll transaction(s) for ${escapeHtml(mo.month)}.`:'<b>Payroll has not been committed for this month.</b>'}</p>
      <button class="btn btn-accent" id="openPay">Open Payroll Planning</button>
    </div>`; })()}
    <div class="card stack-section">
      <div class="small-btn-row" style="flex-wrap:wrap;gap:8px;">
        <button class="btn" id="copyPrev">Copy Previous Month (manual items)</button>
        <button class="btn" id="addManual">+ Add Manual Item</button>
        ${plan&&plan.status!=='Committed'?`<button class="btn" id="markReviewed">Mark Reviewed</button>`:''}
      </div>
      <p class="hint" style="margin-top:8px;">Build Preview shows committed payroll (read-only) plus recurring expenses due and any copied manual items. Copy Previous Month brings only manual operational items forward — actuals are never copied and every row starts as Planned.</p>
    </div>
    <div id="planArea"></div>`;

  const syncMonth = ()=>{ const m=+document.getElementById('planMonthSel').value; const y=+document.getElementById('planYearSel').value; State.planGenMonth=mkKey(y,m); State.planPreview=null; renderMonthlyPlanGenerator(main); };
  document.getElementById('planMonthSel').addEventListener('change', syncMonth);
  document.getElementById('planYearSel').addEventListener('change', syncMonth);
  const opb=document.getElementById('openPay'); if(opb) opb.addEventListener('click', ()=>{ State.payrollMonth=monthKey; hrNavTo('payroll'); });
  document.getElementById('buildPreview').addEventListener('click', ()=>{ State.planPreview = buildMonthlyPreview(monthKey, {payroll:true, recurring:true, copyRows:(State.planPreview&&State.planPreview.monthKey===monthKey)?State.planPreview.rows.filter(r=>r.type==='manual').map(r=>({uraian:r.label,category:r.category,planned:r.planned})):[]}); renderMonthlyPlanGenerator(main); });
  document.getElementById('copyPrev').addEventListener('click', ()=>{
    const pk = prevMonthKey(monthKey);
    const items = manualItemsForMonth(pk);
    if(!items.length){ toast(`No manual items to copy from ${keyToMonthObj(pk).month} ${keyToMonthObj(pk).year}.`); return; }
    const copyRows = items.map(t=>({uraian:t.uraian, category:t.category, planned:t.planned}));
    const base = (State.planPreview&&State.planPreview.monthKey===monthKey) ? State.planPreview : buildMonthlyPreview(monthKey, {payroll:true, recurring:true});
    // merge copied manual rows (skip if already present)
    copyRows.forEach(cr=>{ if(!base.rows.some(r=>r.type==='manual' && normStr(r.label)===normStr(cr.uraian) && r.category===cr.category)){ const dupTxn=State.txns.find(t=>t.monthKey===monthKey && normStr(t.uraian)===normStr(cr.uraian) && t.category===cr.category); base.rows.push({type:'manual', label:cr.uraian, category:cr.category, planned:num(cr.planned), selected:!dupTxn, dup:dupTxn?'duplicate':'new', warn:null}); } });
    State.planPreview = base;
    renderMonthlyPlanGenerator(main);
    toast(`Copied ${copyRows.length} manual item(s) from ${keyToMonthObj(pk).month}. Actuals reset; status Planned.`, 5000);
  });
  document.getElementById('addManual').addEventListener('click', ()=>openAddManualRow(monthKey, main));
  const mr = document.getElementById('markReviewed'); if(mr) mr.addEventListener('click', async ()=>{
    // UX-006C2C-4 (row 30) — plan status transition; finance.manage, before the status write.
    if(!can(ACTIONS.FINANCE_MANAGE)){ toast('You do not have permission to manage the monthly plan.', 7000); return; }
    const p=ensureMonthlyPlan(monthKey); if(p.status==='Draft') p.status='Reviewed'; p.updatedAt=new Date().toISOString(); await persistMonthlyPlans(); toast('Monthly plan marked Reviewed.'); render(); });

  const area = document.getElementById('planArea');
  if(!preview){ area.innerHTML = `<div class="card"><div class="empty">Choose a month and click <b>Build Preview</b> to assemble payroll, recurring expenses, and any copied items for review before committing.</div></div>`; return; }
  renderPlanPreview(area, preview, main);
}
function openAddManualRow(monthKey, main){
  const cats = [...new Set([...KNOWN_CATEGORIES, ...State.txns.map(t=>t.category)])].filter(c=>c!=='Pendapatan');
  openModalHTML(`
    <h3>Add Manual Operational Item</h3>
    <form id="mForm"><div class="form-grid" style="grid-template-columns:1fr 1fr;">
      <div class="field" style="grid-column:span 2;"><label>Description</label><input class="input" name="uraian" required placeholder="e.g. Team offsite logistics"></div>
      <div class="field"><label>Category</label><select class="input" name="category">${cats.map(c=>`<option ${c==='Operasional Kegiatan'?'selected':''}>${escapeHtml(c)}</option>`).join('')}</select></div>
      <div class="field"><label>Planned Amount (Rp)</label><input class="input" type="number" step="any" name="planned" required></div>
    </div><div class="modal-actions"><button type="button" class="btn" id="mCancel">Cancel</button><button type="submit" class="btn btn-accent">Add to Preview</button></div></form>`, {onMount:(root)=>{
      root.querySelector('#mCancel').addEventListener('click', closeModal);
      root.querySelector('#mForm').addEventListener('submit', ev=>{
        ev.preventDefault(); const fd=new FormData(ev.target);
        const base = (State.planPreview&&State.planPreview.monthKey===monthKey)?State.planPreview:buildMonthlyPreview(monthKey,{payroll:true,recurring:true});
        base.rows.push({type:'manual', label:(fd.get('uraian')||'').trim(), category:fd.get('category'), planned:num(fd.get('planned')), selected:true, dup:'new', warn:num(fd.get('planned'))<=0?'zero-value':null});
        State.planPreview=base; closeModal(); renderMonthlyPlanGenerator(main);
      });
    }});
}
function renderPlanPreview(area, preview, main){
  const t = previewTotals(preview);
  const typeLabel = {payroll:'Payroll', recurring:'Recurring', manual:'Manual'};
  const warnPills = r=> (r.dup==='duplicate'?'<span class="pill pill-status-cancelled">duplicate</span> ':'') + (r.warn?`<span class="pill pill-status-partial">${r.warn}</span>`:'');
  area.innerHTML = `
    <div class="card stack-section">
      <h3>Plan Preview — ${escapeHtml(keyToMonthObj(preview.monthKey).month)} ${keyToMonthObj(preview.monthKey).year}</h3>
      <div class="grid grid-4" style="margin-bottom:12px;">
        <div class="chart-mini-stat"><div class="lbl">Payroll</div><div class="val">${fmtIDRShort(t.payroll)}</div></div>
        <div class="chart-mini-stat"><div class="lbl">Recurring</div><div class="val">${fmtIDRShort(t.recurring)}</div></div>
        <div class="chart-mini-stat"><div class="lbl">Operational</div><div class="val">${fmtIDRShort(t.manual)}</div></div>
        <div class="chart-mini-stat"><div class="lbl">Total Planned</div><div class="val">${fmtIDRShort(t.total)}</div></div>
      </div>
      <div class="small-btn-row" style="margin-bottom:10px;">
        <button class="btn btn-sm" id="selAllNew">Select all new</button>
        <button class="btn btn-sm" id="unselAll">Unselect all</button>
        <span class="hint" style="align-self:center;">${t.rows} row(s) selected · ${preview.rows.length} total · ${t.dup} duplicate · ${t.missing} missing salary · ${t.zero} zero-value</span>
      </div>
      ${(preview.warnings.length||t.dup||t.missing)?`<div class="insight-list" style="margin-bottom:12px;">
        ${preview.warnings.map(w=>`<div class="insight-item warn">${escapeHtml(w)}</div>`).join('')}
        ${t.dup?`<div class="insight-item warn">${t.dup} row(s) already exist for this month and are unchecked — committing will not duplicate them.</div>`:''}
      </div>`:''}
      <div class="table-wrap" style="max-height:480px;overflow-y:auto;">
        <table>
          <thead><tr><th style="width:34px;"></th><th>Type</th><th>Description</th><th>Category</th><th class="num">Planned</th><th>Flags</th><th></th></tr></thead>
          <tbody>${preview.rows.map((r,i)=>`<tr>
            <td><input type="checkbox" data-sel="${i}" ${r.selected?'checked':''}></td>
            <td><span class="pill pill-other">${typeLabel[r.type]}</span></td>
            <td>${escapeHtml(r.label)}</td>
            <td>${categoryPill(r.category)}</td>
            <td class="num"><input class="input" style="width:110px;text-align:right;padding:4px 6px;" type="number" step="any" data-amt="${i}" value="${num(r.planned)}" ${r.type==='payroll'?'disabled title="Edit payroll amounts on the Payroll Planning page"':''}></td>
            <td>${warnPills(r)||'<span class="faint">—</span>'}</td>
            <td><button class="btn btn-sm" data-remove="${i}">Remove</button></td>
          </tr>`).join('') || '<tr><td colspan="7" class="empty">Nothing to plan for this month.</td></tr>'}</tbody>
        </table>
      </div>
      <div class="modal-actions" style="justify-content:flex-start;margin-top:var(--space-4);">
        <button class="btn btn-accent" id="commitPlan">Commit Selected Rows</button>
        <span class="hint" style="align-self:center;">Creates planned transactions (status: Planned). Existing rows are never duplicated; historical transactions are never deleted.</span>
      </div>
    </div>`;
  area.querySelectorAll('[data-sel]').forEach(cb=>cb.addEventListener('change', e=>{ preview.rows[+e.target.dataset.sel].selected=e.target.checked; renderPlanPreview(area, preview, main); }));
  area.querySelectorAll('[data-amt]').forEach(inp=>inp.addEventListener('input', e=>{ preview.rows[+e.target.dataset.amt].planned=e.target.value; }));
  area.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click', e=>{ preview.rows.splice(+e.target.dataset.remove,1); renderPlanPreview(area, preview, main); }));
  area.querySelector('#selAllNew').addEventListener('click', ()=>{ preview.rows.forEach(r=>{ if(r.dup!=='duplicate') r.selected=true; }); renderPlanPreview(area, preview, main); });
  area.querySelector('#unselAll').addEventListener('click', ()=>{ preview.rows.forEach(r=>r.selected=false); renderPlanPreview(area, preview, main); });
  area.querySelector('#commitPlan').addEventListener('click', async ()=>{
    const sel = preview.rows.filter(r=>r.selected && r.dup!=='duplicate');
    if(!sel.length){ toast('No new rows selected to commit.'); return; }
    if(!confirm(`Commit ${sel.length} row(s) to the ${keyToMonthObj(preview.monthKey).month} plan?\n\nPlanned transactions will be created (status: Planned). Nothing is executed automatically.`)) return;
    const res = await commitMonthlyPlan(preview);
    // SPR-082 — inspect the result BEFORE any completion behaviour. Clearing the
    // preview is completion behaviour: it discards the rows the user was
    // committing, which is exactly the context they need in order to review the
    // data manually. The failure path therefore keeps the preview and shows no
    // success toast. The message never claims a rollback, because none happened.
    // UX-006C2C-4 — a denial is not a partial persistence failure: nothing was written, so
    // the SPR-082 wording below ("some data may already have been saved") would be false.
    // The preview is deliberately retained so the user keeps their rows.
    if(res.error === 'NotAuthorized'){ showWarning('You do not have permission to commit the monthly plan.'); return; }
    if(!res.ok){
      showError('Monthly Plan commit did not complete successfully. Some data may already have been saved. Run Integrity Check and review the Monthly Plan and Finance transaction before retrying.', null, 9000);
      render();
      return;
    }
    State.planPreview=null;
    toast(`Monthly plan committed: ${res.created} planned transaction(s) created.`, 5000);
    render();
  });
}
