CREATE TABLE audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  occurred_at DATETIME(6) NOT NULL,
  actor_user_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  actor_membership_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  action VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  entity VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  entity_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_user_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  request_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  fields VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NULL,
  PRIMARY KEY (id),
  UNIQUE KEY audit_events_company_id (company_id, id),
  KEY audit_events_company_time (company_id, occurred_at),
  KEY audit_events_entity (company_id, entity, entity_id),
  CONSTRAINT audit_events_company_fk FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT audit_events_actor_user_fk FOREIGN KEY (actor_user_id) REFERENCES users (id),
  CONSTRAINT audit_events_actor_membership_fk FOREIGN KEY (actor_membership_id) REFERENCES memberships (id),
  CONSTRAINT audit_events_target_user_fk FOREIGN KEY (target_user_id) REFERENCES users (id),
  CONSTRAINT audit_events_action CHECK (action IN ('employee.create', 'employee.update', 'employee.delete')),
  CONSTRAINT audit_events_entity CHECK (entity IN ('employee')),
  CONSTRAINT audit_events_entity_id CHECK (entity_id <> ''),
  CONSTRAINT audit_events_fields CHECK (fields REGEXP '^[a-z][A-Za-z]{0,31}(,[a-z][A-Za-z]{0,31})*$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
