CREATE TABLE overtime_records (
  id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  company_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  month_key CHAR(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  overtime_date DATE NULL,
  hours DECIMAL(5,2) NOT NULL,
  work_description VARCHAR(160) NULL,
  notes TEXT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY overtime_records_company_id (company_id, id),
  KEY overtime_records_month (company_id, month_key, employee_id),
  KEY overtime_records_employee (company_id, employee_id, month_key),
  CONSTRAINT overtime_records_company_fk FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT overtime_records_employee_fk FOREIGN KEY (company_id, employee_id) REFERENCES employees (company_id, id),
  CONSTRAINT overtime_records_id CHECK (id REGEXP '^[0-9a-f]{32}$'),
  CONSTRAINT overtime_records_month_key CHECK (month_key REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT overtime_records_date_in_month CHECK (overtime_date IS NULL OR (YEAR(overtime_date) = CAST(SUBSTRING(month_key, 1, 4) AS UNSIGNED) AND MONTH(overtime_date) = CAST(SUBSTRING(month_key, 6, 2) AS UNSIGNED))),
  CONSTRAINT overtime_records_hours CHECK (hours > 0 AND hours <= 744 AND MOD(hours * 100, 25) = 0),
  CONSTRAINT overtime_records_status CHECK (status IN ('Draft', 'Submitted', 'Reviewed', 'Rejected')),
  CONSTRAINT overtime_records_version CHECK (version >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
