CREATE TABLE payroll_plans (
  id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  company_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  month_key CHAR(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_code_snapshot VARCHAR(32) NOT NULL,
  employee_name_snapshot VARCHAR(160) NOT NULL,
  department_snapshot VARCHAR(120) NULL,
  base_salary DECIMAL(15,2) NOT NULL,
  overtime_amount DECIMAL(17,2) NOT NULL,
  overtime_hours DECIMAL(9,2) NOT NULL,
  overtime_count INT UNSIGNED NOT NULL,
  total_amount DECIMAL(17,2) NOT NULL,
  calculated_at DATETIME(6) NOT NULL,
  committed_at DATETIME(6) NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  live_key TINYINT UNSIGNED AS (CASE WHEN status = 'Cancelled' THEN NULL ELSE 1 END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY payroll_plans_company_id (company_id, id),
  UNIQUE KEY payroll_plans_live (company_id, month_key, employee_id, live_key),
  KEY payroll_plans_employee (company_id, employee_id, month_key),
  CONSTRAINT payroll_plans_company_fk FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT payroll_plans_employee_fk FOREIGN KEY (company_id, employee_id) REFERENCES employees (company_id, id),
  CONSTRAINT payroll_plans_id CHECK (id REGEXP '^[0-9a-f]{32}$'),
  CONSTRAINT payroll_plans_month_key CHECK (month_key REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT payroll_plans_status CHECK (status IN ('Draft', 'Reviewed', 'Ready', 'Committed', 'Cancelled')),
  CONSTRAINT payroll_plans_committed CHECK ((status = 'Committed') = (committed_at IS NOT NULL)),
  CONSTRAINT payroll_plans_snapshot CHECK (employee_code_snapshot <> '' AND employee_name_snapshot <> ''),
  CONSTRAINT payroll_plans_base_salary CHECK (base_salary > 0),
  CONSTRAINT payroll_plans_overtime CHECK (overtime_amount >= 0 AND overtime_amount = FLOOR(overtime_amount) AND overtime_hours >= 0 AND MOD(overtime_hours * 100, 25) = 0 AND (overtime_count = 0) = (overtime_hours = 0) AND (overtime_count > 0 OR overtime_amount = 0)),
  CONSTRAINT payroll_plans_total CHECK (total_amount >= overtime_amount AND total_amount = FLOOR(total_amount)),
  CONSTRAINT payroll_plans_version CHECK (version >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
