CREATE TABLE supplemental_payrolls (
  id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  company_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payroll_plan_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  month_key CHAR(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_code_snapshot VARCHAR(32) NOT NULL,
  employee_name_snapshot VARCHAR(160) NOT NULL,
  department_snapshot VARCHAR(120) NULL,
  overtime_amount DECIMAL(17,2) NOT NULL,
  overtime_hours DECIMAL(9,2) NOT NULL,
  overtime_count INT UNSIGNED NOT NULL,
  calculated_at DATETIME(6) NOT NULL,
  committed_at DATETIME(6) NULL,
  commit_idempotency_key CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  open_key TINYINT UNSIGNED AS (CASE WHEN status IN ('Draft', 'Reviewed', 'Ready') THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY supplemental_payrolls_company_id (company_id, id),
  UNIQUE KEY supplemental_payrolls_open (company_id, payroll_plan_id, open_key),
  UNIQUE KEY supplemental_payrolls_commit_key (company_id, commit_idempotency_key),
  KEY supplemental_payrolls_month (company_id, month_key, employee_id),
  CONSTRAINT supplemental_payrolls_company_fk FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT supplemental_payrolls_plan_fk FOREIGN KEY (company_id, payroll_plan_id) REFERENCES payroll_plans (company_id, id),
  CONSTRAINT supplemental_payrolls_employee_fk FOREIGN KEY (company_id, employee_id) REFERENCES employees (company_id, id),
  CONSTRAINT supplemental_payrolls_id CHECK (id REGEXP '^[0-9a-f]{32}$'),
  CONSTRAINT supplemental_payrolls_month_key CHECK (month_key REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT supplemental_payrolls_status CHECK (status IN ('Draft', 'Reviewed', 'Ready', 'Committed', 'Cancelled')),
  CONSTRAINT supplemental_payrolls_committed CHECK ((status = 'Committed') = (committed_at IS NOT NULL)),
  CONSTRAINT supplemental_payrolls_commit_key_committed CHECK ((status = 'Committed') = (commit_idempotency_key IS NOT NULL)),
  CONSTRAINT supplemental_payrolls_commit_key_format CHECK (commit_idempotency_key REGEXP '^[0-9a-f]{32}$'),
  CONSTRAINT supplemental_payrolls_snapshot CHECK (employee_code_snapshot <> '' AND employee_name_snapshot <> ''),
  CONSTRAINT supplemental_payrolls_amount CHECK (overtime_amount > 0 AND overtime_amount = FLOOR(overtime_amount)),
  CONSTRAINT supplemental_payrolls_hours CHECK (overtime_hours > 0 AND MOD(overtime_hours * 100, 25) = 0),
  CONSTRAINT supplemental_payrolls_count CHECK (overtime_count > 0),
  CONSTRAINT supplemental_payrolls_version CHECK (version >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
