CREATE TABLE finance_postings (
  id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  company_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_kind VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payroll_plan_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  supplemental_payroll_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  employee_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  month_key CHAR(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount DECIMAL(17,2) NOT NULL,
  status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  idempotency_key CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  posted_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY finance_postings_company_id (company_id, id),
  UNIQUE KEY finance_postings_payroll_plan (company_id, payroll_plan_id),
  UNIQUE KEY finance_postings_supplemental_payroll (company_id, supplemental_payroll_id),
  UNIQUE KEY finance_postings_idempotency_key (company_id, idempotency_key),
  KEY finance_postings_month (company_id, month_key, employee_id),
  CONSTRAINT finance_postings_company_fk FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT finance_postings_payroll_plan_fk FOREIGN KEY (company_id, payroll_plan_id) REFERENCES payroll_plans (company_id, id),
  CONSTRAINT finance_postings_supplemental_payroll_fk FOREIGN KEY (company_id, supplemental_payroll_id) REFERENCES supplemental_payrolls (company_id, id),
  CONSTRAINT finance_postings_employee_fk FOREIGN KEY (company_id, employee_id) REFERENCES employees (company_id, id),
  CONSTRAINT finance_postings_id CHECK (id REGEXP '^[0-9a-f]{32}$'),
  CONSTRAINT finance_postings_source CHECK (source_kind IN ('payrollPlan', 'supplementalPayroll') AND (source_kind = 'payrollPlan') = (payroll_plan_id IS NOT NULL) AND (source_kind = 'supplementalPayroll') = (supplemental_payroll_id IS NOT NULL)),
  CONSTRAINT finance_postings_month_key CHECK (month_key REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT finance_postings_amount CHECK (amount > 0 AND amount = FLOOR(amount)),
  CONSTRAINT finance_postings_status CHECK (status = 'Planned'),
  CONSTRAINT finance_postings_idempotency_key_format CHECK (idempotency_key REGEXP '^[0-9a-f]{32}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
