CREATE TABLE finance_executions (
  id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  company_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  finance_posting_id CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  month_key CHAR(7) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  amount DECIMAL(17,2) NOT NULL,
  executed_on DATE NOT NULL,
  payment_method VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  idempotency_key CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  recorded_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY finance_executions_company_id (company_id, id),
  UNIQUE KEY finance_executions_finance_posting (company_id, finance_posting_id),
  UNIQUE KEY finance_executions_idempotency_key (company_id, idempotency_key),
  KEY finance_executions_month (company_id, month_key, employee_id),
  CONSTRAINT finance_executions_company_fk FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT finance_executions_finance_posting_fk FOREIGN KEY (company_id, finance_posting_id) REFERENCES finance_postings (company_id, id),
  CONSTRAINT finance_executions_employee_fk FOREIGN KEY (company_id, employee_id) REFERENCES employees (company_id, id),
  CONSTRAINT finance_executions_id CHECK (id REGEXP '^[0-9a-f]{32}$'),
  CONSTRAINT finance_executions_month_key CHECK (month_key REGEXP '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT finance_executions_amount CHECK (amount > 0 AND amount = FLOOR(amount)),
  CONSTRAINT finance_executions_payment_method CHECK (payment_method IN ('cash', 'bankTransfer', 'qris', 'virtualAccount', 'creditCard', 'other')),
  CONSTRAINT finance_executions_idempotency_key_format CHECK (idempotency_key REGEXP '^[0-9a-f]{32}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
